name: Build Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - interface_module/firmware/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: interface_module/firmware

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Verify PlatformIO
        run: pio --version

      - name: Install libraries
        run: pio pkg install
      - name: Build firmware
        run: pio run -e esp32doit-devkit-v1
      - name: Build SPIFFS image
        run: pio run -e esp32doit-devkit-v1 --target buildfs

      - name: Debug
        run: ls -la .pio/build/esp32doit-devkit-v1

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: firmware
          path: |
            .pio/build/esp32doit-devkit-v1/firmware.bin
            .pio/build/esp32doit-devkit-v1/spiffs.bin
